/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Comp1: typeof import('./src/components/comp1/comp1.vue')['default']
    Comp2: typeof import('./src/components/comp2/comp2.vue')['default']
    Comp3: typeof import('./src/components/comp3/comp3.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
  }
}
